language: cpp

matrix:
  include:
    - compiler: g++-8
      env:
        - MATRIX_EVAL = "CXX=g++-8"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libboost-graph-dev

    - compiler: clang-9
      env:
        - MATRIX_EVAL = "CXX=clang++-9"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
          packages:
            - clang-9
            - libboost-graph-dev

script:
 - make
 - ./example
