language: cpp

matrix:
  include:
    - compiler: g++-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libboost-all-dev

    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty
          packages:
            - clang-9
            - libboost-all-dev

script:
 - make
 - ./example
