language: cpp

compiler:
 - gcc
 - clang

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libboost-all-dev
      env: CXX=g++-8

    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
          packages:
            - clang-8
            - libboost-all-dev
      env: CXX=clang-8

script:
 - make
 - ./example
