language: cpp

matrix:
  include:
    - compiler: g++-8
      env:
        - CXX_COMPILER=g++-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libboost-graph-dev

    - compiler: clang-8
      env:
        - CXX_COMPILER=clang++-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
          packages:
            - clang-8
            - libboost-graph-dev

before_install:
  - export CXX=$CXX_COMPILER

script:
 - make
 - ./example
