language: cpp

os: linux

dist: trusty

compiler:
 - gcc
 - clang

addons:
  apt:
   sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty

   packages:
    - clang-9
    - g++9
    - libboost-all-dev

script:
 - make
 - ./example
